# 해당 파일에서는 Tensor에 대해서 다뤄보도록 하겠습니다 

In [2]:
import torch
import numpy as np

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

print(x_data)
print(f"type : {x_data.dtype}")

tensor([[1, 2],
        [3, 4]])
type : torch.int64


In [4]:
print('Tensor로 변환 이전 ')
data = np.array([[3,4],[5,6]])
print(x_data)
print(f"type : {data.dtype}")


print('\n\nTensor로 변환 이후 ')
x_data = torch.from_numpy(data)
print(x_data)
print(f"type : {x_data.dtype}")


Tensor로 변환 이전 
tensor([[1, 2],
        [3, 4]])
type : int64


Tensor로 변환 이후 
tensor([[3, 4],
        [5, 6]])
type : torch.int64


In [5]:
data_random = torch.rand_like(x_data, dtype = torch.float64)
print(data_random)

data_ones = torch.ones_like(x_data, dtype = int)
print(data_ones)

tensor([[0.8714, 0.8041],
        [0.5671, 0.7247]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1]])


In [6]:
shape = (2, 3)

data_rand = torch.rand(shape)
data_one = torch.ones(shape)
data_zero = torch.zeros(shape)
print(f'data_rand : {data_rand}')
print(f'data_one : {data_one}')
print(f'data_zero : {data_zero}')

data_rand : tensor([[0.8954, 0.2224, 0.1574],
        [0.4063, 0.5789, 0.2716]])
data_one : tensor([[1., 1., 1.],
        [1., 1., 1.]])
data_zero : tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
data = np.array([[1,2,3], [4,5,6], [7,8,9]])
data = torch.from_numpy(data)

print(f'shape of data : {data.shape}')
print(f'type of data : {data.dtype}')
print(f'device of data : {data.device}')

shape of data : torch.Size([3, 3])
type of data : torch.int64
device of data : cpu


# 현재 data의 모양은 아래와 같습니다.

[ [ 1, 2, 3 ], 
  [ 4, 5, 6 ]]

In [12]:
data = torch.tensor([[1,2,3],[4,5,6]])

device = 'cuda' if torch.cuda.is_available() else 'cpu'
data.to(device= device)

print(f'데이터의 첫 row들 만 출력 한다 : {data[0, :]}')
print(f'데이터의 첫 col 만 출력 합니다 : {data[ :, 0]}')

데이터의 첫 row들 만 출력 한다 : tensor([1, 2, 3])
데이터의 첫 col 만 출력 합니다 : tensor([1, 4])


# Matrix를 이어 붙히는 함수
 : cat 함수의 경우 이어붙히는 dim을 제외하고 모든 dim이 동일한 경우 matrix 연결이 가능합니다.

In [14]:
shape1 = (3, 3, 4)
shape2 = (2, 3, 4)


data1 = torch.rand(shape1, dtype = torch.float64)
data2 = torch.rand(shape2, dtype = torch.float64)


# dim = 0 을 기준으로 이어 붙히기 ( 가능 )
cated_data = torch.cat([data1, data2], dim = 0)
print(f'Cat with dim = 0  : {cated_data}')

# dim = 1을 기준으로 이어붙히기 ( 불가능 ) Becuae cat을 이용해서 붙히는 경우 붙히는 dim을 제외하고 모두 차원이 일치해야하기 떄문이다.
cated_data = torch.cat([data1, data2], dim = 1)
print(f'Cat with dim = 1  : {cated_data}')


Cat with dim = 0  : tensor([[[0.0507, 0.3797, 0.0540, 0.2655],
         [0.6903, 0.6066, 0.0741, 0.7928],
         [0.9267, 0.5205, 0.8880, 0.6348]],

        [[0.2603, 0.2377, 0.5654, 0.4458],
         [0.7734, 0.1331, 0.0402, 0.8221],
         [0.9377, 0.5711, 0.8049, 0.2890]],

        [[0.1427, 0.6058, 0.2903, 0.0740],
         [0.7023, 0.8390, 0.0375, 0.6411],
         [0.1705, 0.1568, 0.5848, 0.8156]],

        [[0.2029, 0.2286, 0.3311, 0.5289],
         [0.1753, 0.9947, 0.8983, 0.7227],
         [0.5901, 0.2461, 0.0437, 0.7034]],

        [[0.9272, 0.8712, 0.7768, 0.9266],
         [0.2264, 0.1627, 0.4118, 0.2711],
         [0.1764, 0.6219, 0.8221, 0.8244]]], dtype=torch.float64)


RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 3 but got size 2 for tensor number 1 in the list.

# Tensor의 산술 연산 

    > matmul을 수행하는 tensor들의 마지막 2개의 차원만 잘 맞춰주면된다. 예를들어 shape이 (2,4,.....,k,p)이면  (2,4,.....,p,t) 이런식으로 p의 차원만 잘 맞춰주면 된다

In [22]:
# 행렬 곱 
shape1 = (3, 4)
shape2 = (4, 2)

data1 = torch.rand(shape1)
data2 = torch.rand(shape2)

result1 = data1 @ data2
result2 = data1.matmul(data2)
print(f'Tensro의 행렬곱 ( 내적 ) 결과')
print(f'@ 사용 : {result1}')
print('\n')
print(f'matmul 사용 : {result1}')


print('========= 고차원의 tensor matmul 실행 =========')

shape1 = (2,3,4,2,4,23,5,2,9)
shape2 = (2,3,4,2,4,23,5,9,4)

torch1 = torch.randn(shape1)
torch2 = torch.randn(shape2)
result = torch1.matmul(torch2)
print(result)
print(f'result 형탱 : {result.shape}')


Tensro의 행렬곱 ( 내적 ) 결과
@ 사용 : tensor([[2.2154, 1.9714],
        [1.4578, 1.6657],
        [1.1044, 0.9277]])


matmul 사용 : tensor([[2.2154, 1.9714],
        [1.4578, 1.6657],
        [1.1044, 0.9277]])
========= 고차원의 tensor matmul 실행 =========
tensor([[[[[[[[[-2.8120e+00,  1.6066e+00,  2.0255e+00,  4.6095e+00],
               [-5.3773e+00, -6.9249e-01,  2.1154e+00,  6.5450e+00]],

              [[ 2.0201e+00, -2.1297e+00,  7.9226e-01, -2.3218e-01],
               [-3.4234e-02, -4.2734e+00,  1.1226e+00,  4.7863e-01]],

              [[ 1.0959e+00, -2.9900e+00, -1.7099e-01,  8.2369e-01],
               [-9.0767e+00,  7.4749e+00, -6.9019e-01,  2.3019e+00]],

              [[ 6.4915e+00, -4.9825e+00, -2.9100e+00, -5.5733e-01],
               [-4.4866e+00,  3.1834e+00, -2.9437e+00,  1.4565e+00]],

              [[ 2.2993e+00,  1.2575e+00, -1.0728e+00,  1.1768e+00],
               [ 1.2049e-01,  7.4389e-01,  4.7475e-02, -5.1659e-01]]],


             [[[-2.6642e+00,  3.3644e+00,  3.0118e+00, 

# Tensor의 elementwise 곱 연산

In [28]:
data1 = torch.tensor([[1,2,3],[4,5,6]])
data2 = torch.tensor([[2,3,4], [5,6,7]])


result = data1.mul(data2)
print(result, end = '\n\n')

result = data1 * data2
print(result)

tensor([[ 2,  6, 12],
        [20, 30, 42]])

tensor([[ 2,  6, 12],
        [20, 30, 42]])


# single-element tensor : 모든 값을 하나로 집계

In [42]:
print('======= 1D에 대한 agg======')
data = torch.tensor([1,2,3,4,5])
agg = data.sum()
print(agg)

agg = agg.item()
print(agg)


print('======== 2D 에 대한 agg =======')
data = torch.tensor([[1,2,3,4],[2,3,4,5]])


print('agg = data.sum(dim = 0) : ', data.sum(dim = 0))
print('agg = data.sum(dim = 1) : ', data.sum(dim = 1) )
print('agg = data.sum() : ', data.sum())


# 아래 2개의 값은 단일 값을 갖지 않기 때문에 .item()이 불가능하다
# print(f'data.sum(dim = 0).item() = ', data.sum(dim = 0).item())
# print(f'data.sum(dim = 1).item() = ', data.sum(dim = 1).item())
print('agg = data.sum().item() : ', data.sum().item())


======= 1D에 대한 agg======
tensor(15)
15
======== 2D 에 대한 agg =======
agg = data.sum(dim = 0) :  tensor([3, 5, 7, 9])
agg = data.sum(dim = 1) :  tensor([10, 14])
agg = data.sum() :  tensor(24)
agg = data.sum().item() :  24


# in_place 연산. 연산결과를 바로 피연산자에 저장하는 역할을 수행합니다

In [43]:
data = torch.tensor([[1,2,3,4,], [5,6,7,8], [9,10,11,12]])
# 따로 대입하지 않아도 바로 data변수가 바뀌게 된다.
data.add_(100)
print(data)

tensor([[101, 102, 103, 104],
        [105, 106, 107, 108],
        [109, 110, 111, 112]])


# Numpy롤 변경
> cpu 상에서 numpy와 tensor는 메모리를 공유하고 있기에 하나를 변경하는 경우 다른 하나도 변경되게 된다.

In [46]:
tensor1 = torch.tensor([[1,2,3],[4,5,6]])

print(f'tensor : {tensor1}', end = '\n\n')

numpy1 = tensor1.numpy()
print(f'numpy : {numpy1}')

tensor : tensor([[1, 2, 3],
        [4, 5, 6]])

numpy : [[1 2 3]
 [4 5 6]]


In [47]:
tensor1.add_(100)

print(f'tensor : {tensor1}')
print(f'numpy : {numpy1}')

tensor : tensor([[101, 102, 103],
        [104, 105, 106]])
numpy : [[101 102 103]
 [104 105 106]]
