### bool을 활용해서 ndarray의 idx 참조가 가능합니다.

In [16]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
even_arr = arr1[arr1 % 2 == 0].copy() # 꼭 copy()를 사용해서 원본 ndarray에 손상이 가지 않도록 설정해야합니다.
print(even_arr) 

even_arr = even_arr * 2
print(even_arr)
print(arr1)

[2 4 6]
[ 4  8 12]
[1 2 3 4 5 6]


#### ndarray에서 기본으로 지원하는 범용함수 .abs() | .exp() | .sqrt()

In [17]:
arr = np.array([1,2,-3,4,5,-6])

print(f'.abs() : {np.abs(arr)}')
print(f'.exp() : {np.exp(arr)}')
print(f'.sqrt() : {np.sqrt(arr)}')

.abs() : [1 2 3 4 5 6]
.exp() : [2.71828183e+00 7.38905610e+00 4.97870684e-02 5.45981500e+01
 1.48413159e+02 2.47875218e-03]
.sqrt() : [1.         1.41421356        nan 2.         2.23606798        nan]


/var/folders/gf/3r9shwfs5ydc_872y235kv5r0000gn/T/ipykernel_99681/3107454106.py:5: RuntimeWarning: invalid value encountered in sqrt
  print(f'.sqrt() : {np.sqrt(arr)}')


### Numpy에서 지원하는 집합 함수

In [18]:
arr1 = np.array([1,2,3,3,2,2,1,1,1,1,1,6])
arr2 = np.array([4,4,4,4,2,2,2,1,1,1,1,1,6])

print(f'np.unique() : {np.unique(arr1)}')
print(f'np.union1d : {np.union1d(arr1, arr2)}')
print(f'np.intersect1d : {np.intersect1d(arr1, arr2)}')
print(f'np.setdiff1d : {np.setdiff1d(arr1, arr2)}')
print(f'np.setdiff1d : {np.setdiff1d(arr2, arr1)}')

np.unique() : [1 2 3 6]
np.union1d : [1 2 3 4 6]
np.intersect1d : [1 2 6]
np.setdiff1d : [3]
np.setdiff1d : [4]


### Numpy에서 random 배열 생성하기

In [19]:
shape = (2,3)
# random.randint()의 인자는 (시작숫자, 끝숫자, 형태) 를 의미한다.
arr1 = np.random.randint(1, 100, shape)
print(arr1)


# 0 ~ 1 사이의 난수 생성 : uniform distribution을 따른다.
arr2 = np.random.rand(2,3)
print(arr2)

# Nomal distribution을 따른다.
arr3 = np.random.randn(2,3)
print(arr3)

[[29 48 56]
 [27 51 50]]
[[0.46894661 0.57103144 0.96748901]
 [0.59723667 0.67962299 0.66853646]]
[[-3.00624628e-01  2.30625927e-01  4.38925040e-02]
 [ 1.31488010e-01 -3.21394507e-01  9.65269490e-05]]


### 2차원 ndarry Shape과 Reshape 함수

In [25]:
# shape을 사용하게 되면 ndarray의 형태를 파악할 수 있다.
arr1 = np.random.randint(0, 100, (4,3,2,4,2))
print(arr1.shape)

# reshape을 활용해서 ndarray의 형태를 변경할수 있다.
arr2 = arr1.reshape(12, 8, -1)
print(arr2.shape)



(4, 3, 2, 4, 2)
(12, 8, 2)


### 2차원 ndarray에서의 인덱스 참조와 슬라이스

In [32]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10], [3,2,1,4,2]])

print('row : 2, col : 2 = ' ,arr1[2,2])
print(f'row : 전체, col : 2 ~ 3까지 : \n', arr1[ : , 2 : 4])


row : 2, col : 2 =  1
row : 전체, col : 2 ~ 3까지 : 
 [[3 4]
 [8 9]
 [1 4]]


### 2D ndarray에서 axis 개념을 통해서 축을 결정가능하다.

In [42]:
# 1D 에서는 axis = 0 한개 뿐이다.
print('===== 1D =====')
arr1 = np.array([1,2,3])
print(arr1.sum(axis= 0))

# 2D 에서는 axis = 0, 1 2개가 존재한다.
print('===== 2D =====')

arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2.sum(axis = 0)) # row 방향으로 
print(arr2.sum(axis = 1)) # col 방향으로 
# 3D 에서는 axis = = 0, 1, 2 3개가 존재한다.
print('===== 3D =====')

arr3 = np.array([ [ [1,2],[3,4]], [[4,2], [4,1]] , [[5,1], [2, 4] ] ])
print(arr3.sum(axis=0)) # 높이 방향
print(arr3.sum(axis = 1)) # row 방향
print(arr3.sum(axis = 2)) # col qkdgid

===== 1D =====
6
===== 2D =====
[5 7 9]
[ 6 15]
===== 3D =====
[[10  5]
 [ 9  9]]
[[4 6]
 [8 3]
 [7 5]]
[[3 7]
 [6 5]
 [6 6]]


In [47]:
arr = np.array([ [ [1,2],[3,4]], [[4,2], [4,1]] , [[5,1], [2, 4] ] ])

print(f'arr[0] :', arr[0])
print(f'arr[1] :', arr[1])
print(f'arr[2] :', arr[2])

print('\n\n')

print(f'arr[0][0] : ', arr[0][0])

print('\n\n')
print(f'arr[0][0][0] : ', arr[0][0][0])

arr[0] : [[1 2]
 [3 4]]
arr[1] : [[4 2]
 [4 1]]
arr[2] : [[5 1]
 [2 4]]



arr[0][0] :  [1 2]



arr[0][0][0] :  1


### 팬시 인덱스 참조 ( 정수나 boolen으로 이루어진 배열로 다른 배열을 참조하는 기능을 의미)

In [48]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = np.array([0, 2, 4, 6, 8])

print(arr1[arr2]) # 다음과 같이 다른 ndarray를 사용해서 원하는 index의 값만을 사용 가능하다.


[1 3 5 7 9]


### 전치 행렬 

In [58]:
# .T 를 사용해서 전치를 표현할 수 있다.
arr = np.random.randint(0, 100, (4, 6))
print(arr.shape)
arrT = arr.T
print(arrT.shape)

print('_____________________________________________________________________')
# .transpose()를 사용해서 전치를 표현할 수 있다.
arr = np.random.randint(0, 100, (4, 6))
print(arr.shape)
arrT = np.transpose(arr)
print(arrT.shape)
print('_____________________________________________________________________')

arr = np.random.randint(0, 100, (4, 6))
print(arr.shape)
arrT = np.swapaxes(arr, 0, 1)
print(arrT.shape)

(4, 6)
(6, 4)
_____________________________________________________________________
(4, 6)
(6, 4)
_____________________________________________________________________
(4, 6)
(6, 4)


In [67]:
# 3D 이상이 되면 transpose()와 swapaxes()는 축을 설정 해줘야한다.
print('_________________________T______________________________')

arr = np.random.randint(0, 100, (2,4,3,5,5,9))
print(arr.shape)
arrT = arr.T
print(arrT.shape)
print('_________________________transpose______________________________')

arr = np.random.randint(0, 100, (2,4,3,5,5,9))
print(arr.shape)
arrT = np.transpose(arr)
print(arrT.shape)

print('_________________________swapaxes__________________________')
arr = np.random.randint(0, 100, (2,4,3,5,5,9))
print(arr.shape)
arrT = np.swapaxes(arr, 0, 2) # 교체를 원하는 축을 입력하게 됩니다.
print(arrT.shape)


_________________________T______________________________
(2, 4, 3, 5, 5, 9)
(9, 5, 5, 3, 4, 2)
_________________________transpose______________________________
(2, 4, 3, 5, 5, 9)
(9, 5, 5, 3, 4, 2)
_________________________swapaxes__________________________
(2, 4, 3, 5, 5, 9)
(3, 4, 2, 5, 5, 9)


### 정렬

In [76]:
print('# 1D 에서 정렬하기')
arr = np.array([1,2,3,4,5])
print(np.sort(arr))
print(np.sort(arr)[::-1])

print('# 2D에서 축별로 정렬하기')
arr= np.array([[1,3,2],[9,5,6]])
print(np.sort(arr, axis = 0))
print(np.sort(arr, axis = 1))


# 1D 에서 정렬하기
[1 2 3 4 5]
[5 4 3 2 1]
# 2D에서 축별로 정렬하기
[[1 3 2]
 [9 5 6]]
[[1 2 3]
 [5 6 9]]


### 행렬 계산

In [83]:
# .dot()을 활용하게 된다.
arr1 = np.random.randint(1, 100, (2,4))
arr2 = np.random.randint(1, 100, (4,2))
print(arr1.dot(arr2).shape)

arr1 = np.random.randint(1, 100, (2,4,4,3,2,3,4))
arr2 = np.random.randint(1, 100, (9,2,2,2,5,4,10))
print(arr1.dot(arr2).shape)

(2, 2)
(2, 4, 4, 3, 2, 3, 9, 2, 2, 2, 5, 10)


### 통계 함수 ( mean, max, argmax, argmin)

In [89]:
arr = np.array([[1,2,3,4,5,6,7], [4,2,5,1,2,4,12]])
print(f'meam axis = 0 : {np.mean(arr, axis=0)}')

# argmax의 경우 값이 가장 큰 element의 index를 반환한다.
print(f'argmax axis = 0 : {np.argmax(arr, axis=0)}')
print(f'argmax axis = 1 : {np.argmax(arr, axis=1)}')



meam axis = 0 : [2.5 2.  4.  2.5 3.5 5.  9.5]
argmax axis = 0 : [1 0 1 0 0 0 1]
argmax axis = 1 : [6 6]


### 브로드캐스트

In [90]:
import numpy as np

# 2D 배열
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# 1D 배열
arr2 = np.array([10, 20, 30])

# 브로드캐스팅을 통한 더하기 연산
result = arr1 + arr2

print("arr1:\n", arr1)
print("arr2:", arr2)
print("Result of broadcasting:\n", result)

arr1:
 [[1 2 3]
 [4 5 6]]
arr2: [10 20 30]
Result of broadcasting:
 [[11 22 33]
 [14 25 36]]


In [94]:
arr1 = np.random.randint(1, 100, (2,4,3,5,2))
arr2 = np.random.randint(1, 100, (2,4,3,5,1))

print((arr1 + arr2).shape)

(2, 4, 3, 5, 2)
